#!/usr/bin/env python3
"""
check_staleness.py

Compares do_not_track.env against the toptout dataset and reports:
  - Variables in toptout but not in our file (potential additions)
  - Variables in our file but not in toptout (potential staleness)

Exits 1 if there are any findings, 0 if fully in sync.
"""

import json
import re
import sys
import time
from pathlib import Path

import requests

TOPTOUT_CONTENTS_URL = (
    "https://api.github.com/repos/beatcracker/toptout/contents/data"
)
ENV_FILE = Path(__file__).parent.parent / "do_not_track.env"
SESSION = requests.Session()
SESSION.headers.update({"Accept": "application/vnd.github+json"})


def get_with_retry(url: str, max_attempts: int = 5) -> requests.Response:
    """GET with exponential back-off on 429 / 5xx responses."""
    for attempt in range(max_attempts):
        resp = SESSION.get(url, timeout=30)
        if resp.status_code == 200:
            return resp
        if resp.status_code == 429 or resp.status_code >= 500:
            wait = 2 ** attempt
            print(
                f"  [warn] HTTP {resp.status_code} for {url} — retrying in {wait}s",
                file=sys.stderr,
            )
            time.sleep(wait)
            continue
        resp.raise_for_status()
    raise RuntimeError(f"Failed to fetch {url} after {max_attempts} attempts")


def read_local_vars() -> set[str]:
    """Return the set of env var names declared in do_not_track.env."""
    pattern = re.compile(r"^([A-Z_][A-Z0-9_]*)=")
    vars_found: set[str] = set()
    for line in ENV_FILE.read_text().splitlines():
        m = pattern.match(line)
        if m:
            vars_found.add(m.group(1))
    return vars_found


def fetch_toptout_vars() -> dict[str, list[str]]:
    """
    Return a mapping of env var name -> list of tool names that declare it.

    Only includes tools that have at least one env var defined.
    """
    print("Fetching toptout data index…", file=sys.stderr)
    index = get_with_retry(TOPTOUT_CONTENTS_URL).json()

    json_files = [
        entry for entry in index if entry["name"].endswith(".json")
    ]
    print(
        f"  Found {len(json_files)} tool definition files.", file=sys.stderr
    )

    var_to_tools: dict[str, list[str]] = {}
    for entry in json_files:
        url = entry["download_url"]
        try:
            data = get_with_retry(url).json()
        except Exception as exc:
            print(f"  [warn] Skipping {entry['name']}: {exc}", file=sys.stderr)
            continue

        tool_name = data.get("name", entry["name"])
        telemetry_entries = data.get("telemetry", [])
        for tel in telemetry_entries:
            for env_entry in tel.get("env", []):
                var_name = env_entry.get("name", "").strip()
                if var_name:
                    var_to_tools.setdefault(var_name, []).append(tool_name)

    return var_to_tools


def main() -> int:
    local_vars = read_local_vars()
    toptout_map = fetch_toptout_vars()
    toptout_vars = set(toptout_map.keys())

    in_toptout_not_local = sorted(toptout_vars - local_vars)
    in_local_not_toptout = sorted(local_vars - toptout_vars)

    if not in_toptout_not_local and not in_local_not_toptout:
        print("do_not_track.env is fully in sync with the toptout dataset. No action needed.")
        return 0

    lines: list[str] = []
    lines.append("## Staleness Check Findings")
    lines.append("")
    lines.append(
        "The monthly staleness check found differences between "
        "`do_not_track.env` and the "
        "[toptout dataset](https://github.com/beatcracker/toptout)."
    )
    lines.append("")

    if in_toptout_not_local:
        lines.append(
            f"### Variables in toptout but not in `do_not_track.env` ({len(in_toptout_not_local)})"
        )
        lines.append("")
        lines.append(
            "These may be candidates to add. Review each tool to confirm "
            "the variable opts out of telemetry."
        )
        lines.append("")
        lines.append("| Variable | Tool(s) |")
        lines.append("| --- | --- |")
        for var in in_toptout_not_local:
            tools = ", ".join(toptout_map[var])
            lines.append(f"| `{var}` | {tools} |")
        lines.append("")

    if in_local_not_toptout:
        lines.append(
            f"### Variables in `do_not_track.env` but not in toptout ({len(in_local_not_toptout)})"
        )
        lines.append("")
        lines.append(
            "These may have been removed upstream or were added locally "
            "outside of toptout. Review each one to confirm it is still valid."
        )
        lines.append("")
        for var in in_local_not_toptout:
            lines.append(f"- `{var}`")
        lines.append("")

    lines.append("---")
    lines.append(
        "_Generated by [check_staleness.py](../blob/main/scripts/check_staleness.py)_"
    )

    print("\n".join(lines))
    return 1


if __name__ == "__main__":
    sys.exit(main())
